### ISSUE TITLE
Exclude Pinned Topics From Archiver?

### ISSUE THREAD

**Issue by timimasa** [julianlam/nodebb-plugin-archiver#6]
Hi. This is not really an issue, but it would be nice if we can excluded pinned topics from the auto archiver. Is this possible?

**Comment by julianlam** [comment]
This seems like an obvious feature :smile: Let me see what I can do...

**Comment by julianlam** [comment]
@timimasa -- in my testing, it already excludes pinned tids...

**Comment by timimasa** [comment]
> @timimasa -- in my testing, it already excludes pinned tids...

Hmm, I just ran another test and the archiver locked my pinned topics. Is there an option in admin to exclude pinned topics? We only need to archive topics that are not pinned and keep the pinned topics forever (or as long as we could).

**Comment by julianlam** [comment]
Hmm... what version of NodeBB are you running? We've stored pinned topics in a separate set `cid:<cid>:tids:pinned` since Nov 2016 (v1.4.0), and archiver just didn't get updated to check those sorted sets, so there isn't a way for a pinned topic to become archived anymore.

Unless the topic is in both sorted sets? You'd have to verify for me by diving into your database. Let me know if you need help on what to look for...

**Comment by timimasa** [comment]
I'm on the latest version of NodeBB (v1.17.1). I'll look into sorted sets and let you know if I have any questions.

**Comment by timimasa** [comment]
> Hmm... what version of NodeBB are you running? We've stored pinned topics in a separate set `cid:<cid>:tids:pinned` since Nov 2016 (v1.4.0), and archiver just didn't get updated to check those sorted sets, so there isn't a way for a pinned topic to become archived anymore.
> 
> Unless the topic is in both sorted sets? You'd have to verify for me by diving into your database. Let me know if you need help on what to look for...

Hi @julianlam , I created a few pinned topics to test and ran the archiver, but it still tells me that the pinned items that I created days ago will get archived. 

I was thinking maybe the reason why the archiver archived pinned topics in the past was because the topics were created before 1.17 (topics were created in 1.16). 

Let assumed that they are in both sets, what could cause this issue?

**Comment by julianlam** [comment]
@timimasa So to clarify, newly pinned topics don't trip up archiver, right?

In that case, can you unpin and repin those old topics, and test? That will probably resolve the issue,

> Let's assumed that they are in both sets, what could cause this issue?

Most likely what happened is @barisusakli changed the way pinned topics were stored so it was easier to retrieve them or paginate through a category's topics without having to handle the pinned topics.

**Comment by timimasa** [comment]
> @timimasa So to clarify, newly pinned topics don't trip up archiver, right?
> 
> In that case, can you unpin and repin those old topics, and test? That will probably resolve the issue,
> 
> > Let's assumed that they are in both sets, what could cause this issue?
> 
> Most likely what happened is @barisusakli changed the way pinned topics were stored so it was easier to retrieve them or paginate through a category's topics without having to handle the pinned topics.

I tried to unpin and repin old and new topics, but these topics are still being archived. 

Now, I'm curious if I am the only one having this issue.

**Comment by julianlam** [comment]
> Now, I'm curious if I am the only one having this issue.

@timimasa Might be, might not be. That's the fun thing with bugs! :laughing: 

So to clarify, you *don't* see this happening to newly pinned topics? Just old topics that were pinned, and you've tried unpinning and repinning, to no avail?

**Comment by timimasa** [comment]
> So to clarify, you _don't_ see this happening to newly pinned topics? Just old topics that were pinned, and you've tried unpinning and repinning, to no avail?
> 
It's happening to old and new pinned topics. Yes, I've tried unpinning and repinning, but to no avail. 

It's almost as if the archiver is not seeing or respecting pinned topics when ran. 

By the way, thank you for your assistance with this. :)

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-archiver/blob/master/index.js#L91-L95

Looks like it will archive pinned topics as well if no category is specified because it will use `topics:tid` sorted set which contains all topic ids.

**Comment by julianlam** [comment]
Aaaaah... that's good to know, thanks for the context @barisusakli

**Comment by julianlam** [comment]
v5 of archiver now can exclude pinned topics if toggled on via the ACP.

It is considered a breaking change because previous behaviour had pinned topics archived if no categories were selected, and pinned topics excluded if there were.

The behaviour has now been standardised so it will adhere to the ACP option.
