### ISSUE TITLE
[Feature] Archive / Delete users with 0 post counts based on time of registration or connection

### ISSUE THREAD

**Issue by MaxWaldorf** [julianlam/nodebb-plugin-archiver#9]
Hey guys,

As for posts, I would like to remove users that have:
- 0 posts
- Registered since XXXXX
(or)
- No activities since XXXXX

Thank you for your help and great plugin!

**Comment by MaxWaldorf** [comment]
Bump

**Comment by julianlam** [comment]
Hi @MaxWaldorf -- while I like the idea, I simply do not always have time to add the functionality in a timely manner, but I do appreciate the reminder.

As always, my repos are open to PRs, and I will try to implement features when time permits :smile:

**Comment by MaxWaldorf** [comment]
No worries, take your time!
